namespace spaar.ModLoader
{
  /// <summary>
  /// All block prefabs in the game. These values can be used as indices to
  /// MachineObjectTracker.AllPrefabs.
  /// </summary>
  public enum Prefab
  {
#pragma warning disable CS1591 // Don't need documentation for each of these
    StartingBlock = 0,
    DoubleWoodenBlock = 1,
    Wheel = 2,
    MetalBlade = 3,
    Decoupler = 4,
    Hinge = 5,
    MetalBall = 6,
    Brace = 7,
    Unused = 8,
    Spring = 9,
    WoodenPanel = 10,
    Cannon = 11,
    Unused2 = 12,
    SteeringBlock = 13,
    FlyingBlock = 14,
    SingleWoodenBlock = 15,
    Suspension = 16,
    CircularSaw = 17,
    Piston = 18,
    Swivel = 19,
    Spike = 20,
    Flamethrower = 21,
    SpinningBlock = 22,
    Bomb = 23,
    ArmorPlateSmall = 24,
    Wing = 25,
    Propeller = 26,
    Grabber = 27,
    SteeringHinge = 28,
    ArmorPlateRound = 29,
    BombHolder = 30,
    FlameBall = 31,
    ArmorPlateLarge = 32,
    Plow = 33,
    WingPanel = 34,
    Ballast = 35,
    Boulder = 36,
    HalfPipe = 37,
    CogMediumUnpowered = 38,
    CogMediumPowered = 39,
    WheelUnpowered = 40,
    WoodenPole = 41,
    Slider = 42,
    Balloon = 43,
    BallJoint = 44,
    RopeWinch = 45,
    LargeWheel = 46,
    Torch = 47,
    Drill = 48,
    GripPad = 49,
    SmallWheel = 50,
    CogLargeUnpowered = 51,
    Unused3 = 52,
    ShrapnelCannon = 53,
    Grenade = 54,
    SmallPropeller = 55,
    WaterCannon = 56,
    Pin = 57,
    CameraBlock = 58,
    Rocket = 59,
    LargeWheelUnpowered = 60,
  }
#pragma warning restore CS1591
}