namespace spaar.ModLoader
{
  /// <summary>
  /// All block types in the game. These values can be used as indices to
  /// AddPiece.blockTypes.
  /// </summary>
#pragma warning disable CS1591 // Don't need documentation for each of these
  public enum BlockType
  {
    SmallWoodBlock = 0,
    SteeringPiece = 1,
    Blade = 2,
    MetalBall = 3,
    GroundPegNail = 4,
    WoodPanel2joints = 5,
    Brace = 6,
    HingeCube = 7,
    SpringOld = 8,
    Spring = 9,
    Wheel = 10,
    ExplosiveDecoupler = 11,
    Canon = 12,
    Chain = 13,
    FlyingSpiral = 14,
    SingleWoodBlock = 15,
    Suspension = 16,
    SawDisc = 17,
    Piston = 18,
    HingeRound = 19,
    Spike = 20,
    Flamethrower = 21,
    SpinningBlock = 22,
    BombBlock = 23,
    MetalArmourPlateSmall = 24,
    DaVinciWing = 25,
    Propellor = 26,
    Grabber = 27,
    SteeringHinge = 28,
    MetalArmourPlateRound = 29,
    BombHolder = 30,
    FlameBallBlock = 31,
    MetalArmourPlate2 = 32,
    Plow = 33,
    WingPanel = 34,
    Ballast = 35,
    Boulder = 36,
    HalfPipe = 37,
    CogMediumFree = 38,
    CogMediumPowered = 39,
    WheelFree = 40,
    WoodenPole2 = 41,
    Slider = 42,
    BalloonSmall = 43,
    BallAndSocket = 44,
    RopeSimple = 45,
    LargeWheel = 46,
    SmallFlameTorch = 47,
    Drill = 48,
    GripPad = 49,
    SmallWheel = 50,
    CogLargeFree = 51,
    SmallPropellorBuildPoint = 52,
    ShrapnelCannon = 53,
    GrenadeBlock = 54,
    SmallPropellor = 55
  }

  /// <summary>
  /// All block prefabs in the game. These values can be used as indices to
  /// MachineObjectTracker.AllPrefabs.
  /// </summary>
  public enum Prefab
  {
    StartingBlock = 0,
    SmallWoodBlock = 1,
    Wheel = 2,
    Blade = 3,
    ExplosiveDecoupler = 4,
    HingeCube = 5,
    MetalBall = 6,
    Brace = 7,
    SpringOld = 8,
    Spring = 9,
    WoodPanel2joints = 10,
    Canon = 11,
    Chain = 12,
    SteeringPiece = 13,
    FlyingSpiral = 14,
    SingleWoodBlock = 15,
    Suspension = 16,
    SawDisc = 17,
    Piston = 18,
    HingeRound = 19,
    Spike = 20,
    Flamethrower = 21,
    SpinningBlock = 22,
    BombBlock = 23,
    MetalArmourPlateSmall = 24,
    DaVinciWing = 25,
    Propellor = 26,
    Grabber = 27,
    SteeringHinge = 28,
    MetalArmourPlateRound = 29,
    BombHolder = 30,
    FlameBallBlock = 31,
    MetalArmourPlate2 = 32,
    Plow = 33,
    WingPanel = 34,
    Ballast = 35,
    Boulder = 36,
    HalfPipe = 37,
    CogMediumFree = 38,
    CogMediumPowered = 39,
    WheelFree = 40,
    WoodenPole2 = 41,
    Slider = 42,
    BalloonSmall = 43,
    BallAndSocket = 44,
    RopeSimple = 45,
    LargeWheel = 46,
    SmallFlameTorch = 47,
    Drill = 48,
    GripPad = 49,
    SmallWheel = 50,
    CogLargeFree = 51,
    SmallPropellorBuildPoint = 52,
    ShrapnelCannon = 53,
    GrenadeBlock = 54,
    SmallPropellor = 55
  }
#pragma warning restore CS1591

}
